apiVersion: v1
kind: Service
metadata:
  name: {{ include "proglog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "proglog.labels" . | nindent 4}}
spec:
  # clusterIP を None と定義することで、headless サービス (単一のIPにロードバランスしない) を定義
  # ※当該分散サービス独自のサービスディスカバリ手段を持っているため
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: rpc
      port: {{ .Values.rpcPort }}
      targetPort: {{ .Values.rpcPort }}
    - name: serf-tcp
      protocol: "TCP"
      port: {{ .Values.serfPort }}
      targetPort: {{ .Values.serfPort }}
    - name: serf-udp
      protocol: "UDP"
      port: {{ .Values.serfPort }}
      targetPort: {{ .Values.serfPort }}
  # 以下セレクタの定義により、k8sの endpoint controller がサービスを動作させるポッドのレコードを返すようDNS設定を変更する
  # ※各ポッドが独自のDNSレコードを取得することで、それぞれのサーバは互いを発見できるようになる。
  selector: {{ include "proglog.selectorLabels" . | nindent 4 }}
